# Generated by Django 5.2.7 on 2026-03-15 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('current_location', models.CharField(max_length=200)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FireStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('accident', 'Road Accident'), ('fire', 'Fire Emergency'), ('crime', 'Crime Emergency'), ('disaster', 'Natural Disaster')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('police', 'Police'), ('fire', 'Fire Service'), ('hospital', 'Hospital')], max_length=50)),
                ('assigned_to', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.emergency')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.emergency')),
            ],
        ),
    ]
