# Generated by Django 5.2.7 on 2026-03-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='citizen',
            name='medical_issue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='trusted_contact1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='citizen',
            name='trusted_contact2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='address',
            field=models.TextField(),
        ),
    ]
