# Generated by Django 5.2.7 on 2026-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_citizen_blood_group_citizen_medical_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergency',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='trusted_contact1',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='trusted_contact2',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
