# Generated by Django 5.2.7 on 2026-03-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_citizen_is_admin_emergency_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='trusted_contact2',
            new_name='trusted_contact1_email',
        ),
        migrations.RenameField(
            model_name='citizen',
            old_name='trusted_contact1',
            new_name='trusted_contact2_email',
        ),
        migrations.AddField(
            model_name='citizen',
            name='trusted_contact1_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='citizen',
            name='trusted_contact2_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
