# Generated by Django 5.2.7 on 2026-03-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_trusted_contact2_citizen_trusted_contact1_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.citizen')),
            ],
        ),
    ]
